### ISSUE TITLE
mobile o thik dekha jar na. 

### ISSUE THREAD

**Issue by monwarqx1250** [Tawhidul54/form#3]
mobile o form ita thik kori dekha jar na. ulta palta dekhay. thik moto input o deya jay na. design baje oi gese kintu computer o thik kori e dekhar sob
![Screenshot_20241221_142949](https://github.com/user-attachments/assets/f166f913-c4a7-4393-96bd-8b42864dfeaa)

**Comment by Tawhidul54** [comment]
thank you sir amra ota thik korsi

**Comment by Tawhidul54** [comment]
ha tik hoyse
